server:
  port: 9003

spring:
  zipkin:
    base-url: http://localhost:9411/zipkin/
  application:
    name: contact2-service

eureka:
  instance:
    hostname: localhost

    management:
      tracing:
      sampling:
        probability: 1.0